name: 🪲 Bug Report
description: Help us help you:Report those pesky bugs!
title: "[Bug]: "
labels: ["needs triage"]
projects: ["SpaceHub"]

body:
  - type: markdown
    attributes:
      value: |
        ## Important!

        Before filing your issue, ask yourself:
        - Do I have an idea of where the issue occurs?
        - Did I include clear steps to reproduce it?
        - Could it be due to my own mistakes?
        - Has this bug already been reported?

  - type: checkboxes
    attributes:
      label: Basic troubleshooting.
      description: The project is built with Docusaurus. Review these items before submitting an issue to ensure you’ve completed the necessary steps.
      options:
        - label: I'm using the latest version of Docusaurus.
          required: true
        - label: I have tried the `npm run clear` or `yarn clear` command.
        - label: I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
        - label: I have tried creating a repro with https://new.docusaurus.io.
        - label: I have read the console error message carefully (if applicable).

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened when "
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Kindly indicate the troubleshooting steps you've taken.
      placeholder: |
        1. Navigate to the form page.
        2. Leave required fields empty.
        3. Click the "Submit" button.
        4. Observe the application crash.

    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - DuckDuck Go

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting, you agree to our [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you can contribute, check the box to indicate you're working on it. Please submit a pull request within 7 days.
      options:
        - label: I'd be willing to address this documentation request myself.
