name: 🐞 Bug Report
description: Report an issue related to documentation
labels: ["bug", "needs triage"]
projects: ["projects/4"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this bug report.
        [Learn more](https://mkeithx.pages.dev/community/contributing#issues).

  - type: dropdown
    id: issue
    attributes:
      label: Issue category
      description: What's the issue about?
      multiple: false
      options:
        - Undocumented API
        - Elaboration needed
        - Outdated or incorrect information
        - Formatting or readability improvement
        - Others
    validations:
      required: true     

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps you've taken.
      placeholder: |
        1. I've checked ...
        2. Also validated through ...
        3. Including this ...
        4. To support this ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output. Auto-formatted into code.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting, you agree to our [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
