name: 🪲 Bug Report
description: Report those pesky bugs!
title: '[Bug]: '
labels: ["bug","needs triage"]
assignees:
  - mkeithX

body:
  - type: markdown
    attributes:
      value: |
        ## Please help us help you!
        Before filing your issue, we kindly ask you to:
        - Clearly describe the problem in detail, rather than just saying "it doesn't work."
        - Provide a minimal reproduction that we can easily run.
        - Include a live deployment URL that demonstrates the issue (if applicable).
        - Share as much relevant information as possible: code snippets, repository URLs, git branch links, full stack traces, screenshots, and videos.
        - Present your request clearly and concisely, demonstrating that you've put in effort to assist us in helping you.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: In addition, please make sure that you
      options:
        - label: Read the Guidelines in [reporting bugs](https://mkeithx.pages.dev/community/issue/report).
          required: true
        - label: Performed [basic troubleshooting](https://mkeithx.pages.dev/community/issue/style-guide/troubleshoot) (if applicable).
          required: false
        - label: Be willing to address this issue myself.
          required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Kindly indicate the troubleshooting steps you've taken.
      placeholder: |
        1. Navigate to the form page.
        2. Leave required fields empty.
        3. Click the "Submit" button.
        4. Observe the application crash.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        How did you expect your project to behave?
      placeholder: Write what you thought would happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        Describe what exactly happen.
      placeholder: Write what exactly happened.
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device type.
      multiple: false
      options:
        - Mobile
        - Desktop

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting, you agree to our [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
