name: 🐛 Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Prior to submitting your issues, consider the following:
        - Is it clear that there is indeed an issue?
        - Do you have a basic understanding of where things might be going wrong?
        - Is it possible that the problem could be due to something you did?

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    attributes:
      label: Bug description
      description: A description of the 🐛 bug
      placeholder: A concise description of what you're experiencing.
    validations:
      required: true
    
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps taken you've done so far.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://mkeithx.github.io/docs/contributing#contribute)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true

