blank_issues_enabled: false
contact_links:
  - name: 🚀 Feature request
    url: https://mkeithx.github.io/feature-requests
    about: User the Canny board to send feature requests, vote and measure the interest of users.
