blank_issues_enabled: false
contact_links:
  - name: 🚀 Feature Requests
    url: https://mkeithx.pages.dev/feature-requests
    about: Casual Feature Requests
  - name: ❓Simple Question
    url: https://github.com/mkeithX/mkeithx.github.io/issues
    about: Use the tracker and submit an issue
    
