blank_issues_enabled: false
contact_links:
  - name: 🚀 Feature Requests
    url: https://mkeithx.pages.dev/feature-requests
    about: Not ready to open a pull request yet? We got that covered.
  - name: 💡 Proposals
    url: https://forms.office.com/r/sQBiMJ8bQ3
    about: If you intend to make any non-trivial changes to existing implementations, let's discuss the change you wish to make.
