name: 📚 Documentation
description: Report docs related issue.
labels: [documentation, 'status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Documenting undocumented APIs.
        - Elaborating on a particular topic.
        - Updating external links.
        - Anything else that doesn't require touching the codebase itself.

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Read and understand the Contributing Guidelines
      options:
        - label: I have read the Contributing Guidelines on issues.
          required: true
          url: https://mkeithx.github.io/docs/contributing#contribute
