name: 📒 Documentation
description: Report an issue related to documentation
title: '[Docs]: '
labels: ["documentation","needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Help us help you!

        > [!IMPORTANT]  
        > For **DOCUMENTATION-RELATED** issues only.

  - type: dropdown
    id: issue
    attributes:
      label: Use this template if you're having issues related to
      description: Please select the nearest category
      multiple: false
      options:
        - Undocumented API
        - Elaboration needed
        - Outdated or incorrect information
        - Formatting or readability improvement
        - Others (Kindly specify in the description)
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: A clear description of the issue.
      placeholder: Clearly describe the issue/request in detail.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting, you agree to our [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you can contribute, check the box to indicate you're working on it. Please submit a pull request within 7 days.
      options:
        - label: I'd be willing to address this documentation request myself.
          required: false
