name: 📚 Documentation
description: Report an issue related to documentation
labels: [documentation, 'status: needs triage']
assignees:
  - mkeithX
body:
  - type: markdown
    attributes:
      value: |
        ## IMPORTANT

        This template is strictly for documentation-related issues. We ensure our content's accuracy by citing trusted sources like NASA, Wikipedia, and other documentation, including Python and Microsoft. Additionally, we use AI to assist us in creating content faster and more effectively.

        ---

  - type: dropdown
    id: issue
    attributes:
      label: Issue category
      multiple: false
      options:
        - label: Undocumented API
        - label: Elaboration needed on a particular topic
        - label: Outdated or incorrect information
        - label: Formatting or readability improvement
        - label: Others
    validations:
      required: true     

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: input
    attributes:
      label: Links
      description: Relevant urls and/or hyperlinks.
      placeholder: URLs or hyperlinks
    validations:
      required: false  

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps you've taken so far.
      placeholder: |
        1. I've checked ...
        2. Also validated through ...
        3. Including this ...
        4. To support this ...
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true