name: 📒 Documentation
description: Report an issue related to documentation
title: "[Docs]: "
labels: ["needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Important!

        Use this template to report various documentation related issue.
        If documentation issues arise, consider if it’s a documentation or code problem. For code issues, use the "bug" template.

        Pull requests are generally accepted if:
        - Relevant to many users
        - Not about external tooling
        - Not documented elsewhere or hard to find

        You may submit a pull request directly if criteria are met; otherwise, issues are welcome.

  - type: dropdown
    id: issue
    attributes:
      label: Issue category
      description: What's the issue about?
      multiple: false
      options:
        - Undocumented API
        - Elaboration needed
        - Outdated or incorrect information
        - Formatting or readability improvement
        - Others
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: A clear description of the issue.
      placeholder: Tell us what you see!
      value: " "
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label: I have read the [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md).
          required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you can contribute, check the box to indicate you're working on it. Please submit a pull request within 7 days.
      options:
        - label: I'd be willing to address this documentation request myself.
