name: 📚 Documentation
description: Report an issue related to documentation
labels: [documentation, 'status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue

        **Description**

        Please provide a clear and concise description of the documentation issue.

        **Type of Documentation Issue**

        - [ ] Undocumented API
        - [ ] Elaboration needed on a particular topic
        - [ ] Outdated or incorrect information
        - [ ] Formatting or readability improvement
        - [ ] Other (please specify): 

        **Expected Behavior**

        Describe the expected behavior or outcome after resolving this documentation issue.

        **Additional Context**

        Add any other context about the problem here.

        ---
        ℹ️ **Note:** Please make sure you have read and understood the [Contributing Guidelines](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md) before submitting this issue.

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Type of Documentation Issue
      options:
        - label: Undocumented API
        - label: Elaboration needed on a particular topic
        - label: Outdated or incorrect information
        - label: Formatting or readability improvement
        - label: Other (please specify)
