name: 📚 Documentation
description: Report an issue related to documentation
title: "[Docs]: "
labels: [documentation, 'status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Documenting undocumented APIs;
        - Elaborating on a particular topic;
        - Updating external links;
        - anything else that doesn't require touching the codebase itself.




  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

   - type: checkboxes
    attributes:
      label: I have read and understand the Contributing Guidelines.
      options:
        - label: I have read the [Contributing Guidelines on issues](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md#documentation).
          required: true