name: 💅 Feature design / RFC
description: Submit a detailed feature request with a concrete proposal, including an exhaustive API / UI design
labels: [feature, 'status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        Important things:

        - We expect you to submit a feature request including a real design (API / UI...), not just a basic idea.
        - The design does not have to be perfect, we'll discuss it and fix it if needed.
        - For a more "casual" feature request, consider using Canny instead: https://mkeithx.github.io/feature-requests.

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label: I have read the [Contributing Guidelines on issues](https://github.com/mkeithX/mkeithx.github.io/blob/main/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true
