name: 💥 Non-Trivial Issue / Proposal
description: Propose a non-trivial change to The SpaceHub Project
title: "[Proposal]: "
labels: ["needs triage", "feature: proposal"]

body:
  - type: markdown
    attributes:
      value: |
        ## Important!

        If you intend to make any non-trivial changes to existing implementations, we kindly ask you to start by discussing the change you wish to make. This allows us to have an open dialogue about your proposed changes, ensuring that everyone is on the same page and understands the context and goals behind the modification.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What is the problem or proposal?
      placeholder: Provide a clear and concise description of the problem or idea.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Suggest a solution or improvement.
      placeholder: How do you propose to address this issue?
      value: "Outline your proposed solution or improvement."
    validations:
      required: true

  - type: textarea
    id: potential-impacts
    attributes:
      label: Potential Impacts
      description: Discuss any potential impacts of your proposal.
      placeholder: What are the benefits and drawbacks?
      value: "Explain the expected benefits and possible drawbacks of your proposal."
    validations:
      required: true

  - type: checkboxes
    id: agree-to-terms
    attributes:
      label: Agreement
      options:
        - label: I have read the [Code of Conduct](https://github.com/mkeithX/mkeithx.github.io/blob/main/CONTRIBUTING.md).
          required: true
        - label: I understand that this proposal requires discussion.
          required: true
