name: MKX Test Deploy

on:
  pull_request:
    branches:
      - main
      - preview/*

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          # cache: npm

      - name: Install dependencies and build
        run: |
          cd website
          npm ci
          npm run build