name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd website
          npm ci && npm run build

      - name: Test deploy
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # command: pages deploy website --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}

  build:
    name: Build and Deploy Website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: lts/*

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: website/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # command: pages deploy website --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}

# https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler