name: Build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 30
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: Node setup
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
  
        - name: Install Dependencies
          run: |
            cd website
            npm ci && npm run build
      