name: Build and Deploy

on:
  push:
    paths:
      - .github/workflows/build-deploy.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    if: github.ref == 'refs/heads/preview'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 30

    name: Build (Preview)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          cd website
          npm install && npm run build

      - name: Deploy (Preview)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: website/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: preview
  
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 30

    name: Build (Production)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Deploy (Production)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME}}
          directory: website/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main