name: CI test

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      
      - name: Node setup
        uses: actions/setup-node@v4.1.0
        with:
          node-version: lts/*
          

      - name: Install dependencies
        run: |
         cd website
         npm ci && npm run build
