name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd website
          npm ci && npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy website --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}

          
# https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
