on: [push]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    name: Deploy (Preview)
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}

