name: Deploy (Preview)

on: [push]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 30
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      # Run your project's build step
      - name: Install Dependencies
        run: |
            cd website
            npm install && npm run build
            
      - name: Deploy (Preview)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: website/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: preview
