
name: Deploy (Production)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

# concurrency:
#   group: production-${{ github.ref }}
#   cancel-in-progress: true

# on:
#   push:
#     branches:
#       - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

          
      - name: Install Dependencies
        run: |
            cd website
            npm ci && npm run build


      - name: Deploy (Production)
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: website/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
