name: Deploy

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  deploy-production:
    runs-on: ubunto-latest
    timeout-minutes: 30
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: |
            cd website
            npm ci && npm run build

      - name: Deploy
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy website --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
