name: Deploy (Preview)

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      deployments: write
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: |
          cd website
          npm ci && npm run build

      - name: Deploy (Preview)
        uses: cloudflare/wrangler-action@v3
        with:
            workingDirectory: website
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            environment: development
            command: pages deploy website --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
        env:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
