name: Deploy (Preview)

concurrency:
    group: development
    cancel-in-progress: true

on:
  pull_request:
    branches:
      - preview


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          cd website
          npm install && npm run build

  deploy-preview:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    permissions:
        contents: read
        deployments: write
    timeout-minutes: 30

    steps:
        - name: Deploy (Preview)
          uses: cloudflare/pages-action@v1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
            directory: website/build
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
            branch: preview