name: MKX CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/mkx-build.yml'
      - 'website/**'

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: |
          cd website
          npm install && npm run build