on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      # Run your project's build step
      - name: Publish to Cloudflare Pages
        run: |
            cd website
            npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mkeithx # e.g. 'my-project'
          directory: website/build # e.g. 'dist'
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}