name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push event, but only for main branch
  push:
    branches:
      - main
  # Triggers the workflow on pull request event, but only for pull request from not forked repo
  pull_request:
    types:
      - opened
      - synchronize
  # Triggers the workflow on pull request event, but only for pull request opened or pull request labeled with "🚀request-deploy" (from forked repo)
  # pull_request is not allowed to use secrets, so we use pull_request_target instead (in forked repos)
  pull_request_target:
    types:
      # When a created pull request from forked repo, it will be comment 'Should deploy to add label'
      - opened
      # When a labeled '🚀request-deploy' pull request from forked repo, it will be deploy to Cloudflare Pages
      - labeled
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # default contents: read & write (in forked repos, only read)
  contents: write
  # default deployments: read & write (in forked repos, only read)
  deployments: write
  # default pull-requests: read & write (in forked repos, only read)
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    # push event in main branch
    # workflow_dispatch event
    # pull_request event from not forked repo
    # pull_request_target event with label "🚀request-deploy" from forked repo
    if: ${{
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false) ||
      (github.event_name == 'pull_request_target' &&
      github.event.action == 'labeled' &&
      github.event.pull_request.head.repo.fork == true &&
      contains(github.event.label.name, '🚀request-deploy'))
      }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    # Cancel previous runs that are not completed yet
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0

      - name: Remove built-in Yarn
        run: npm uninstall -g yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Build website
        run: yarn build

      - name: Publish to Cloudflare Pages
        id: cloudflare-pages-deploy
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: mkeithx
          directory: build
          workingDirectory: website
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}