name: "Python"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-python:
    name: Build and Test Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4.2.2

      - name: Configure Python Environment
        uses: actions/setup-python@v5.3.0
        
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          cd examples/python-starters
          python -m pip install --upgrade -r requirements.txt

      - name: Run Python
        run: |
          cd examples/python-starters
          python hello.py
          python -c 'import this'
